name: Build Android APK

# Add permissions block
permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main  # Public release
      - dev   # Private test release

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5
    
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Android NDK
      run: |
        ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
        echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/25.2.9519653" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick

    - name: Generate Project
      run: |
        cd android
        chmod +x zork.sh
        ./zork.sh

    - name: Build APK
      run: |
        cd android/zork
        gradle assemble --info

    - name: List Build Directory Contents
      if: always()
      run: |
        echo "Android directory contents:"
        ls -la android/
        echo "Zork directory contents:"
        ls -la android/zork/
        echo "App directory contents:"
        ls -la android/zork/app/
        echo "Build outputs:"
        ls -la android/zork/app/build/outputs/apk/release/ || echo "Release directory not found"

    - name: Set Version Suffix and Release Flags
      id: release_flags
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "version_suffix=" >> $GITHUB_OUTPUT
          echo "is_draft=false" >> $GITHUB_OUTPUT
          echo "is_prerelease=false" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          echo "version_suffix=-dev" >> $GITHUB_OUTPUT
          echo "is_draft=true" >> $GITHUB_OUTPUT
          echo "is_prerelease=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}${{ steps.release_flags.outputs.version_suffix }}
        release_name: Release ${{ github.run_number }}${{ steps.release_flags.outputs.version_suffix }}
        draft: ${{ steps.release_flags.outputs.is_draft }}
        prerelease: ${{ steps.release_flags.outputs.is_prerelease }}
        body: |
          ${{ github.ref == 'refs/heads/dev' && '⚠️ DEVELOPMENT BUILD - FOR TESTING ONLY ⚠️' || 'Stable release' }}
          
          Build from ${{ github.sha }}
          Branch: ${{ github.ref_name }}
          
          Changes in this release:
          ${{ github.event.head_commit.message }}

    - name: Upload Android APK
      uses: actions/upload-release-asset@v1
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./android/zork/app/build/outputs/apk/release/zork.apk
        asset_name: zork-android${{ steps.release_flags.outputs.version_suffix }}.apk
        asset_content_type: application/vnd.android.package-archive
