name: Build Android APK

# Add permissions block
permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main  # or your default branch name
jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5
    
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Android NDK
      run: |
        ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
        echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/25.2.9519653" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick

    - name: Generate Project
      run: |
        cd android
        chmod +x zork.sh
        ./zork.sh

    - name: Build APK
      run: |
        cd android/zork
        gradle assemble --info

    - name: List Build Directory Contents
      if: always()
      run: |
        echo "Android directory contents:"
        ls -la android/
        echo "Zork directory contents:"
        ls -la android/zork/
        echo "App directory contents:"
        ls -la android/zork/app/
        echo "Build outputs:"
        ls -la android/zork/app/build/outputs/apk/release/ || echo "Release directory not found"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Android APK
      uses: actions/upload-release-asset@v1
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./android/zork/app/build/outputs/apk/release/zork.apk
        asset_name: zork-android.apk
        asset_content_type: application/vnd.android.package-archive
